/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(channelizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(167bb3d9cfb713d2d79f74c50f07034c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/channelizer.h>
// pydoc.h is automatically generated in the build directory
#include <channelizer_pydoc.h>

void bind_channelizer(py::module& m)
{

    using channelizer    = ::gr::lora::channelizer;


    py::class_<channelizer, gr::hier_block2,
        std::shared_ptr<channelizer>>(m, "channelizer", D(channelizer))

        .def(py::init(&channelizer::make),
           py::arg("samp_rate"),
           py::arg("center_freq"),
           py::arg("channel_list"),
           py::arg("bandwidth"),
           py::arg("decimation"),
           D(channelizer,make)
        )
        



        ;




}








