/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(controller.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(512fce4847009685d991d6f271ca38fe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/controller.h>
// pydoc.h is automatically generated in the build directory
#include <controller_pydoc.h>

void bind_controller(py::module& m)
{

    using controller    = ::gr::lora::controller;


    py::class_<controller, gr::block, gr::basic_block,
        std::shared_ptr<controller>>(m, "controller", D(controller))

        .def(py::init(&controller::make),
           py::arg("parent"),
           D(controller,make)
        )
        



        ;




}








