/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(message_file_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e9489007885a308eeca55422c9b17f72)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/message_file_sink.h>
// pydoc.h is automatically generated in the build directory
#include <message_file_sink_pydoc.h>

void bind_message_file_sink(py::module& m)
{

    using message_file_sink    = ::gr::lora::message_file_sink;


    py::class_<message_file_sink, gr::block, gr::basic_block,
        std::shared_ptr<message_file_sink>>(m, "message_file_sink", D(message_file_sink))

        .def(py::init(&message_file_sink::make),
           py::arg("path"),
           D(message_file_sink,make)
        )
        



        ;




}








